language: node_js
node_js:
  - 13
services:
  - docker
install:
  - echo "nothing to install"
before_script:
  - echo "no tests"
script:
  - docker --version
  - docker build -t simple-node .
  - docker tag simple-node clavance/simple-node:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push clavance/simple-node
